#!/usr/bin/env bash


this_script_dir=$(dirname $(readlink -f "$0"))

venv="$this_script_dir/venv"

if [ ! -d "$venv" ]
then
    python3 -m venv "$venv"
fi

source "$venv/bin/activate"

pip install --editable "$this_script_dir[dev]"
