name: Basic Checks

on:
  push:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install --editable '.[dev]'
    - run: mypy src
      if: always()
    - run: flake8 src
      if: always()


