name: Basic Checks

on:
  push:

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
    - uses: actions/checkout@v3
    - name: Setup up Python v${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package and dependencies
      run: ./setup_environment
    - name: Mypy type checks
      run: mypy src
      if: always()
    - name: Flake8 linter
      run: flake8 src
      if: always()


