name: Check Price

on:
  push:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install --editable '.[dev]'
    - run: get_current_price --message-if-below 10
      env:
        CALLMEBOT_NUMBER: ${{ secrets.CALLMEBOT_NUMBER }}
        CALLMEBOT_TOKEN: ${{ secrets.CALLMEBOT_TOKEN }}

