name: Routine Message

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * WED'

jobs:
  check-price:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install --editable '.'
    - run: |
        get_current_price --commodity milk --message-price --push-service techulus
        get_current_price --commodity oil --message-price --push-service techulus
      env:
        PUSH_TUCHULUS_API_KEY: ${{ secrets.PUSH_TUCHULUS_API_KEY }}